OfirMatasas/Notify

Notify/Notify/Notify.Android/Notify.Android.csproj, Notify/Notify/Notify.iOS/Notify.iOS.csproj, Notify/Notify/Notify/Forms/FormFriends.xaml, Notify/Notify/Notify/Forms/FormFriends.xaml.cs, Notify/Notify/Notify/Forms/FormGroups.xaml, Notify/Notify/Notify/Forms/FormGroups.xaml.cs, Notify/Notify/Notify/Forms/FormNotifications.xaml, Notify/Notify/Notify/Forms/FormNotifications.xaml.cs, Notify/Notify/Notify/Forms/FormProfile.xaml, Notify/Notify/Notify/Forms/FormProfile.xaml.cs, Notify/Notify/Notify/MainPage.xaml, Notify/Notify/Notify/MainPage.xaml.cs, Notify/Notify/Notify/Notify.csproj
=> Add navigation bar to MainPage

Notify/Notify/Notify/App.xaml.cs, Notify/Notify/Notify/Constants.cs, Notify/Notify/Notify/Forms/FormLogin.xaml, Notify/Notify/Notify/Forms/FormLogin.xaml.cs, Notify/Notify/Notify/Forms/FormProfile.xaml, Notify/Notify/Notify/Forms/FormProfile.xaml.cs, Notify/Notify/Notify/UserCredentials.cs
Using a static user to login to the system, without connecting to the server
https://user-images.githubusercontent.com/88926592/211314421-33604c79-af43-47d1-98f6-9099f17d139f.mov
=> Add login page, with a simple login and logout logic

.github/workflows/main.yml, Notify/Notify.Functions/Notify.Functions/Notify.Functions.csproj, Notify/Notify.Functions/global.json
Using this changes, each time we merge a pull request to our master branch, the Azure Functions app will be redeployed.
=> Edit main.yml file for CD

Notify/Notify/Notify/AppShell.xaml.cs
Fix using incorrect variable in calculating the differ of location.
=> Fix calculation of location differ

Notify/Notify.Functions/Notify.Functions/Core/Constants.cs, Notify/Notify.Functions/Notify.Functions/Notify.Functions.csproj, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/AzureHTTPClients/AzureDatabaseClient.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/DeleteDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/UpdateDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Location/Distance.cs
The client can update / delete their destinations, and it will be saved on database.
Each user will have several destinations (home, work, etc.).
We want those destination to be saved on database, and to be changed / deleted when necessary.
[NOTIFY-54](https://ofirlindekel.atlassian.net/browse/NOTIFY-54)
1. AzureDatabaseClient
2. UpdateDestination
3. DeleteDestination
=> Add destination update/delete on database

Notify/Notify/Notify/Helpers/Constants.cs
Added database's collections constants.
When creating an HTTP request to the database, we want to make sure that we're using the same collections' name, without typos and misspelling.
https://ofirlindekel.atlassian.net/browse/NOTIFY-74?atlOrigin=eyJpIjoiNjk1ZDJkNDlhY2IyNDQyMGI3MDg0YWQ5ZjI2OTIwYWYiLCJwIjoiaiJ9
=> Add database collections constants

Notify/Notify.Functions/Notify.Functions/Core/Constants.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/AzureHTTPClients/AzureDatabaseClient.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/CreateNotification.cs, Notify/Notify/Notify/AppShell.xaml, Notify/Notify/Notify/Helpers/Constants.cs, Notify/Notify/Notify/HttpClient/AzureHttpClient.cs, Notify/Notify/Notify/Notify.csproj, Notify/Notify/Notify/ViewModels/NotificationCreationViewModel.cs, Notify/Notify/Notify/ViewModels/ViewModelLocator.cs, Notify/Notify/Notify/Views/NotificationCreationPage.xaml, Notify/Notify/Notify/Views/NotificationCreationPage.xaml.cs, Notify/Notify/Notify/Views/Views/FriendsListView.xaml, Notify/Notify/Notify/Views/Views/FriendsListView.xaml.cs
This pull request is including several changes:
1. Created a page for creating notification, based on time and location.
2. Create an Azure Function app's function for creating handling a new notification HTTP request from client, and saving it on our CosmosDB database.
3. Switched between profile(home) and notifications icons on navigation bar.
For managing notifications between users.
https://ofirlindekel.atlassian.net/browse/NOTIFY-18?atlOrigin=eyJpIjoiMjQ4MTAwY2IzYWYwNDgxMmFlY2U2NDgxYmZmNTI3NGEiLCJwIjoiaiJ9
1. Xamarin application (creating a new notification)
2. Azure Function (handling the request)
Information is missing in notification creation:
- No notification name
- Unselected notification type
- Unselected location (in case of location type selected)
- No friends selected from …
=> Notification creation page

Notify/Notify.Functions/Notify.Functions/Core/Constants.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/CreateNotification.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/DeleteDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/UpdateDestination.cs
Changed collections' names.
Each collection should have a singular presentation, and the collections are accessible only via Azure Functions app.
=> Fixed collections naming

Notify/Notify.Functions/Notify.Functions/Core/Constants.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/AzureHTTPClients/AzureDatabaseClient.cs
Using the database connection string.
The changes implemented are not working on Azure as expected, causing 500 server error.
=> Fixed database connection string error

Notify/Notify/Notify.Android/Helpers/AndroidLogger.cs, Notify/Notify/Notify.Android/MainActivity.cs, Notify/Notify/Notify.Android/Managers/AndroidWiFiManager.cs, Notify/Notify/Notify.iOS/AppDelegate.cs, Notify/Notify/Notify.iOS/Helpers/IOSLogger.cs, Notify/Notify/Notify.iOS/Managers/iOSBluetoothManager.cs, Notify/Notify/Notify/AppShell.xaml.cs, Notify/Notify/Notify/Bluetooth/BluetoothManager.cs, Notify/Notify/Notify/Core/Destination.cs, Notify/Notify/Notify/Services/LoggerService.cs, Notify/Notify/Notify/ViewModels/FriendsPageViewModel.cs, Notify/Notify/Notify/ViewModels/LocationSettingsPageViewModel.cs, Notify/Notify/Notify/ViewModels/LoginPageViewModel.cs, Notify/Notify/Notify/ViewModels/NotificationsPageViewModel.cs, Notify/Notify/Notify/ViewModels/RegistrationPageViewModel.cs
Implement time based notifications
Main use case in the application.
https://ofirlindekel.atlassian.net/browse/NOTIFY-145?atlOrigin=eyJpIjoiNWNiYjU1NmVlNjc1NDJkN2I4MTA2ZmM2YWNmNzEwMDUiLCJwIjoiaiJ9
* Multiple notifications
* Multiple notifications at the same time
* Elapsed time notifications in case of missing (e.g server down)
* Getting notifications when app is closed.
=> feat: Time based notification

.github/workflows/main.yml, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Database/CreateNotification.cs, Notify/Notify/Notify.Android/Managers/AndroidWiFiManager.cs, Notify/Notify/Notify/AppShell.xaml.cs, Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs, Notify/Notify/Notify/Bluetooth/BluetoothManager.cs, Notify/Notify/Notify/Core/Notification.cs, Notify/Notify/Notify/Helpers/Constants.cs, Notify/Notify/Notify/Helpers/Converter.cs, Notify/Notify/Notify/ViewModels/NotificationCreationViewModel.cs, Notify/Notify/Notify/ViewModels/NotificationDetailsPageViewModel.cs, Notify/Notify/Notify/Views/NotificationCreationPage.xaml, Notify/Notify/Notify/Views/NotificationsPage.xaml, Notify/Notify/Notify/Views/Views/FriendsListView.xaml, Notify/Notify/Notify/Views/Views/NotificationDetailsPage.xaml
When creating a location notification, the notification should be triggered either when arriving or leaving a destination location.
Why do we need those changes?
Not closing, but related to https://ofirlindekel.atlassian.net/browse/NOTIFY-150?atlOrigin=eyJpIjoiMTIwNTI1ODM3NTlmNGUxYWJjMzk1ZjQ0ZjEzM2FkZjAiLCJwIjoiaiJ9
=> Add notification activation to location notifications

Notify/Notify.Functions/Notify.Functions/HTTPClients/AzureDatabaseClient.cs, Notify/Notify.Functions/Notify.Functions/HTTPClients/GoogleHttpClient.cs, Notify/Notify.Functions/Notify.Functions/Notify.Functions.csproj, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Destination/DeleteDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Destination/GetDestinations.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Destination/UpdateDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Friends/CreateFriendRequest.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Friends/GetFriends.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Google/GetAddressSuggestions.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Google/GetCoordinatesFromAddress.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Google/GetDynamicLocations.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Login/CheckUserExists.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Login/Login.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Login/RegisterUser.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Notification/CreateNotification.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Notification/DeleteNotification.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Notification/GetNotifications.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Notification/UpdateNotificationStatus.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Users/GetNotFriendUsers.cs, Notify/Notify/Notify.Android/Managers/AndroidWiFiManager.cs, Notify/Notify/Notify.Android/Notifications/AndroidNotificationManager.cs, Notify/Notify/Notify.iOS/Managers/iOSBluetoothManager.cs, Notify/Notify/Notify.iOS/Notifications/iOSNotificatonManager.cs, Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs, Notify/Notify/Notify/Helpers/Constants.cs, Notify/Notify/Notify/Notifications/INotificationManager.cs
Getting notifications on arrival / leaving a Wi-Fi network.
Notifications can be applied for both arrival to a destination and when leaving it.
Wi-Fi network is one option of the destination settings.
[NOTIFY-155](https://ofirlindekel.atlassian.net/browse/NOTIFY-155)
If the changes are spreading over serveral files, let the reviewer know where to start.
- Connecting to a Wi-Fi network.
- Leaving a Wi-Fi network.
https://github.com/OfirMatasas/Notify/assets/88926592/bafaba79-f26a-41a4-a727-cbaab8c52b96
=> Wi-Fi notification activation

Notify/Notify/Notify/Views/NotificationsPage.xaml
Changing the UI of the notifications page.
The notifications page is too loaded with information, so I've made some cosmetic changes.
I've removed the description column and extended the space of the notification name column.
On top of that, I've changes the hard-coded font size of the table.
=> Modify notifications page

Notify/Notify/Notify/AppShell.xaml.cs, Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs, Notify/Notify/Notify/Core/Destination.cs, Notify/Notify/Notify/Helpers/Converter.cs
Adding functionality of arriving and leaving a destination by location.
Notifications can be triggered by passing a 50 meters radius of a destination, inside or outside.
Those changes implement those triggers.
[NOTIFY-150](https://ofirlindekel.atlassian.net/browse/NOTIFY-150)
- Arriving a destination by location
- Leaving a destination by location
=> Add Arrival & Leave location functionality

Notify/Notify/Notify.Android/Notifications/AndroidNotificationManager.cs, Notify/Notify/Notify.Android/Notifications/NotificationHelper.cs, Notify/Notify/Notify/AppShell.xaml.cs, Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs, Notify/Notify/Notify/Helpers/Constants.cs
Removing the "Sending" status and changed some things over the project.
Some of those changes are fixing the cause of time notifications not turning to expired.
[NOTIFY-181](https://ofirlindekel.atlassian.net/browse/NOTIFY-181)
=> Fix time notification status

Notify/Notify.Functions/Notify.Functions/HTTPClients/GoogleHttpClient.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Destination/DeleteDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Destination/UpdateDestination.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Friend/CreateFriendRequest.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/FriendRequest/AcceptFriendRequest.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/FriendRequest/RejectFriendRequest.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Google/GetDynamicLocations.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Login/CheckUserExists.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Login/Login.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Login/RegisterUser.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/SMS/SendSMS.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Users/UpdateProfilePicture.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Users/UploadProfilePicture.cs, Notify/Notify.Functions/Notify.Functions/Utils/MongoUtils.cs, Notify/Notify/Notify/Core/Destination.cs, Notify/Notify/Notify/Core/Location.cs, Notify/Notify/Notify/Helpers/Converter.cs, Notify/Notify/Notify/ViewModels/ProfilePageViewModel.cs, Notify/Notify/Notify/Views/ProfilePage.xaml
Enable saving an address for the picked geographic location.
When the user picks a place for anyone of his destinations (Home, School, Work), we want to show him what is the address of the location, for better readability.
[NOTIFY-171](https://ofirlindekel.atlassian.net/browse/NOTIFY-171)
- The destination has an address associated with the picked location (and it shows).
- The destination doesn't has an address associated with the picked location (shows nothing for older destinations).
=> Add address to location destination

.github/workflows/main.yml, Notify/Notify/Notify/ViewModels/NotificationsPageViewModel.cs
what are the changes you implemented?
Why do we need those changes?
Put a link to the ticket on Jira we're closing using this pull request.
If the changes are spreading over serveral files, let the reviewer know where to start.
List the scenarios you tested for this changes.
If you implemented a new workflow / fixed a bug in a certain workflow, you can provide a proof it's working here.
=> FIx notifications triggers

.github/workflows/main.yml, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Friend/DeleteFriend.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/FriendRequest/AcceptFriendRequest.cs, Notify/Notify.Functions/Notify.Functions/NotifyFunctions/Notification/GetNotifications.cs, Notify/Notify.Functions/Notify.Functions/Utils/ConversionUtils.cs, Notify/Notify.Functions/Postman/Collections/Friend.postman_collection.json, Notify/Notify.Functions/Postman/Collections/Permission.postman_collection.json, Notify/Notify.Functions/Postman/Collections/User.postman_collection.json, Notify/Notify/Notify/Azure/HttpClient/AzureHttpClient.cs, Notify/Notify/Notify/Core/User.cs, Notify/Notify/Notify/Helpers/Converter.cs, Notify/Notify/Notify/ViewModels/FriendsPageViewModel.cs, Notify/Notify/Notify/ViewModels/NotificationCreationViewModel.cs, Notify/Notify/Notify/Views/FriendsPage.xaml, Notify/Notify/Notify/Views/NotificationsPage.xaml, Notify/Notify/Notify/Views/SubViews/FriendRequestPage.xaml
Improved FriendsPage user interface, according to NotificationPage.
[NOTIFY-164](https://ofirlindekel.atlassian.net/browse/NOTIFY-164)
=> New FriendsPage visualization

Notify/Notify/Notify.Android/Managers/AndroidWiFiManager.cs, Notify/Notify/Notify/AppShell.xaml.cs, Notify/Notify/Notify/Core/Destination.cs, Notify/Notify/Notify/Helpers/Converter.cs, Notify/Notify/Notify/Helpers/Utils.cs
Added a check if location is defined for destination.
=> Fix conflict between destination definition

Notify/Notify/Notify/Core/Notification.cs, Notify/Notify/Notify/Helpers/Converter.cs, Notify/Notify/Notify/ViewModels/NotificationsPageViewModel.cs, Notify/Notify/Notify/Views/NotificationsPage.xaml
what are the changes you implemented?
Why do we need those changes?
Put a link to the ticket on Jira we're closing using this pull request.
If the changes are spreading over serveral files, let the reviewer know where to start.
List the scenarios you tested for this changes.
If you implemented a new workflow / fixed a bug in a certain workflow, you can provide a proof it's working here.
=> Change notification details according to type

Notify/Notify/Notify/Views/FriendsPage.xaml, Notify/Notify/Notify/Views/NotificationsPage.xaml, Notify/Notify/Notify/Views/SubViews/FriendRequestPage.xaml
All profile pictures are having circle shape.
=> Make profile pictures round

Notify/Notify/Notify/Core/Notification.cs, Notify/Notify/Notify/Helpers/Constants.cs, Notify/Notify/Notify/Helpers/Converter.cs, Notify/Notify/Notify/ViewModels/NotificationsPageViewModel.cs, Notify/Notify/Notify/Views/NotificationsPage.xaml
what are the changes you implemented?
Added the ability to accept or reject pending notification
Swipe right to reject a pending notification and swipe left to accept it.
https://ofirlindekel.atlassian.net/browse/NOTIFY-183?atlOrigin=eyJpIjoiOWJlYmY5OGY1OWZmNGZmMGEyZDU1Nzc1NjIzZjZmZDciLCJwIjoiaiJ9
List the scenarios you tested for these changes.
Checked rejecting and to accept a pending notification,
Also checked that remove, renew, and edit notifications work correctly.
https://github.com/OfirMatasas/Notify/assets/82546057/aacbc80a-1bf0-4355-8312-9067b261f482
=> feat: pending notifications operations

Notify/Notify.Functions/Postman/Collections/Notification.postman_collection.json, Notify/Notify/Notify.Android/Managers/AndroidWiFiManager.cs, Notify/Notify/Notify/AppShell.xaml.cs, Notify/Notify/Notify/Bluetooth/BluetoothManager.cs
Send newsfeed for bluetooth and location.
[NOTIFY-202](https://ofirlindekel.atlassian.net/browse/NOTIFY-202)
=> Bluetooth & location newsfeed
